name: Reusable workflow to Deploy Artifacts to AWS

on:
  workflow_call:
   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate-apk:
    runs-on: ubuntu-latest
    steps:
      ################### Steps mentioned in this block would later be moved to the cloud’s login action ####################### 
          # Run build for flutter project.
    - run: flutter build apk
    - run: flutter build appbundle

    # upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk